first_name=input("enter your first name:")
last_name=input("enter your last name:")
print("Hello,",first_name ,last_name,"! Welcome to Python")
print("thank you for using my program")
input("press any key to exit ")